### ISSUE TITLE
Remove empty headings

### ISSUE THREAD

**Issue by chrisbutzke** [stelter/StelterIGXBackend#18]
StelterIGXBackend/Views/Shared/Editable/H3.cshtml
Do we need to add a check for whitespace?

**Comment by PaulSearcy** [comment]
Maybe? 

var title = Model = Ingneniux.Runtime.ICMSElement = Object

Objects can checked for null but not for whitespace. It would be the property of the object  in this case: title.Value. But that value has to be a string primitive or if it's convertible to string, cast it as such. 

Depending on the object's property type the way I cast it to string can differ. String(title.Value) , title.Value.toString(), (string)title.Value 

Then I can do this: title.Value.IsNullOrWhiteSpace()

Reasons explaining all this is that what pages is this used on? I'm going to have to test it out on stelter-dev

**Comment by PaulSearcy** [comment]
Further research and found out that H3.cshtml is _only_ used in LearnHowToFund.cshtml. 
This entails two things 

1. This shouldn't be a seperate file and is trivial to merge into LearnHowToFund.cshtml

2. Due to styling and nature of the element. This element should never be null or whitespace.  Instead the component LearnHowToFund should be disabled. If there's an issue with this it's due to the process not the backend code.

![deanmcgeenoh3](https://user-images.githubusercontent.com/25038336/36509209-8b315672-1724-11e8-8047-ca82bdb81561.JPG)
![sfsymphonynoh3](https://user-images.githubusercontent.com/25038336/36509215-91cded74-1724-11e8-9130-4abbd0fd89ef.JPG)
