### ISSUE TITLE
Add Article Callout (thumbnail listing)

### ISSUE THREAD

**Issue by melissaanderegg** [stelter/StelterIGXBackend#36]
### **Description**
Each article and internal page can have thumbnail listing information, which includes thumbnail text, image, and link text. This thumbnail listing information is called an “Article Callout”. A “Callout" is a thumbnail listing of articles. Articles can be added to the listing by dragging them into the list. 

Article Callouts and Callouts were initially set up in IGX, but did not appear to be used. If you know somewhere these are being used on our sites, please comment here so that we can make sure these updates don’t break older sites.

### **Use Cases**
- On any page, to display related articles (example: https://screencast.com/t/wdd1UNvnqT)
- On a donor story listing page, to display donor stories (example: https://screencast.com/t/e27Z5ByYH0)

### **QA Steps**
Follow the steps below along with any additional testing to QA this new feature. Note issues by leaving comments on this issue in GitHub. 

1. Create a test site in IGX or modify an existing test site
2. On your test site, update the article and interior page templates to include the Article Callout variable
`<div id="stl-callout-container”>@[Callout]</div>`
3. Fill out callout fields on a couple pages to test the thumbnails: (https://screencast.com/t/mEwnFBzTEF)
    1. Article Callout Text
    2. Article Callout Image
    3. Article Callout Link Text (this field will only be available for new Interior and Article pages, since it was added to the schema but not synced)
4. Create a new article page to test the thumbnail listing. Expand the Callout section and drag pages into the Page Name area to add them to the listing (https://screencast.com/t/GcjATR7ui5)
5. Preview your article page. You should see thumbnails for the pages you added to the listing: https://screencast.com/t/5Q5DXJpoOZw. Inspect the styles and note any changes you recommend 
6. There is specific styling for donor story listing (vs a standard article listing). To view this styling, apply the id “donor-listing-page” to your body element. You can do this either in the inspector, or add “donor-listing-page” to the Internal Page Name field in IGX (https://screencast.com/t/yjg0F0jrVeb). You should see the following styles: https://screencast.com/t/FSS9MVsZ. Inspect the styles and note any changes you recommend.
7. Now, try to break it 🙂

**Comment by PaulSearcy** [comment]
Still digging in and researching a solution.

For now the issue is that the **@[Callout]** gets replaced with values from the _Callout_ field in either home or interior schema. 
### CustomInteriorPage.cshtml 
![calloutcustominterior](https://user-images.githubusercontent.com/25038336/43219527-329e08b8-900d-11e8-807f-4a7608d5e0e6.JPG)
### IGX CMS Client Home Page
![calloutexample](https://user-images.githubusercontent.com/25038336/43219448-f3e4dd54-900c-11e8-888e-4199bcd60866.JPG)

Callout is a LinkSet type element in the schemas it used that takes in it's values as components. 
### Home Schema
![calloutschemaexample](https://user-images.githubusercontent.com/25038336/43219467-06aca5de-900d-11e8-802f-a02db7319c55.JPG)

**Comment by PaulSearcy** [comment]
bee769afde06d0c35d9fcb7eb3b6b2f9d8347049 closes this. 
Didn't make the connection right away thanks to the confusing UI
